services:
  - type: web
    plan: free
    name: RenameBot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app & python3 bot.py
    repo: https://github.com/Devil-Botz/RenameBot.git      
    branch: koyeb
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: APP_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: FORCE_SUB 
        sync: false
      - key: DB_NAME 
        sync: false
      - key: DB_URL 
        sync: false 
      - key: START_PIC 
        sync: false
      - key: ADMIN 
        sync: false    
    autoDeploy: false
